server:
  port: 8088

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: accountbank
          uri: lb://accountbank
          predicates:
            - Path=/accountbank/**
        - id: customerbank
          uri: lb://customerbank
          predicates:
            - Path=/customerbank/**